Changes for FR 7.0
ForgeRock/BehavioSec pull request #4
Opened 2020-12-17 20:50 UTC by marcofanti

2020-12-18 16:06 UTC, FrankGasparovic requested changes

2020-12-18 16:06 UTC, FrankGasparovic commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecAuthNode.java
> +            e.printStackTrace();
Use logger instead of print

2020-12-28 14:39 UTC, marcofanti commented
Removed all System.out.println from main branch.

2020-12-28 14:48 UTC, marcofanti commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecBooleanEvaluator.java
> +import com.behaviosec.isdk.entities.Report;
Removed

2020-12-28 14:48 UTC, marcofanti commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecScoreEvaluator.java
> +import com.behaviosec.isdk.config.NoBehavioSecReportException;
Removed

2020-12-28 14:49 UTC, marcofanti commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecAuthNode.java
> +        System.out.println("sendRequest: " + nameValuePairs);
Removed / changed to log...

2020-12-28 14:50 UTC, marcofanti commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecBooleanEvaluator.java
> +            System.out.println("evaluation BehavioSecBooleanEvaluator = " + evaluation);
Removed

2020-12-28 14:50 UTC, marcofanti commented on src/main/java/com/behaviosec/tree/nodes/BehavioSecAuthNode.java
> +            e.printStackTrace();
Changed to logger

2021-01-06 14:13 UTC, merged

2021-01-06 14:15 UTC, marcofanti commented
Updated doc and merged with master